name: Pull Request Review Submitted
# Note: callers must checkout this repo to `./native-github-asana-sync`
inputs:
  trigger-phrase:
    required: true
    type: string
  ref:
    required: false
    type: string
  asana_pat:
    required: true

runs:
  using: "composite"
  steps:
    - name: Find Asana Task in PR description
      uses: ./native-github-asana-sync
      id: find-asana-task-id
      with:
        action: 'find-asana-task-id'
        trigger-phrase: ${{ inputs.trigger-phrase }}

    - name: Add Approved Comment to Asana Task
      if: github.event.review.state == 'approved'      
      uses: ./native-github-asana-sync
      id: post-comment-pr-approved
      with:
        action: 'post-comment-asana-task'
        asana-pat: ${{ inputs.asana_pat }}
        asana-task-id: ${{ steps.find-asana-task-id.outputs.asanaTaskId }}
        asana-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has been approved.'
        asana-task-comment-pinned: true

    - name: Add Changes Requested Comment to Asana Task
      if: github.event.review.state == 'changes_requested'
      uses: ./native-github-asana-sync
      id: post-comment-pr-changes-requested
      with:
        action: 'post-comment-asana-task'
        asana-pat: ${{ inputs.asana_pat }}
        asana-task-id: ${{ steps.find-asana-task-id.outputs.asanaTaskId }}
        asana-task-comment: 'PR: ${{ github.event.pull_request.html_url }} has changed requested.'
        asana-task-comment-pinned: false

    - name: Add Dismissed Comment to Asana Task
      if: github.event.review.state == 'dismissed'
      uses: ./native-github-asana-sync
      id: post-comment-pr-dismissed
      with:
        action: 'post-comment-asana-task'
        asana-pat: ${{ inputs.asana_pat }}
        asana-task-id: ${{ steps.find-asana-task-id.outputs.asanaTaskId }}
        asana-task-comment: 'PR: ${{ github.event.pull_request.html_url }} review has been dismissed.'
        asana-task-comment-pinned: false