name: 'Asana PR Sync'
description: 'Sync GitHub PRs with Asana tasks (Kotlin version)'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  ASANA_ACCESS_TOKEN:
    description: 'Asana access token'
    required: true
  ASANA_WORKSPACE_ID:
    description: 'Asana workspace ID'
    required: true
  ASANA_PROJECT_ID:
    description: 'Asana project ID'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
    
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        ./gradlew run
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ASANA_ACCESS_TOKEN: ${{ inputs.ASANA_ACCESS_TOKEN }}
        ASANA_WORKSPACE_ID: ${{ inputs.ASANA_WORKSPACE_ID }}
        ASANA_PROJECT_ID: ${{ inputs.ASANA_PROJECT_ID }}
