name: Start Privacy Review
on:
  workflow_call:
    inputs:
      trigger-phrase:
        required: false
        type: string
      team_name:
        required: true
        type: string
      ref:
        required: false
        type: string
    secrets:
      asana_pat:
        required: true
      github_pat:
        required: true

jobs:
  start-privacy-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions repo # required so we can reference the actions locally
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          path: actions
          repository: duckduckgo/native-github-asana-sync

      - name: Get PR author Asana ID
        uses: ./actions
        id: get-author-asana-id
        with:
          action: 'get-asana-user-id'
          github-pat: ${{ secrets.github_pat }}

      - name: Find Asana Task in PR description
        uses: ./actions
        id: find-asana-task-id
        with:
          action: 'find-asana-task-id'
          trigger-phrase: ${{ inputs.trigger-phrase }}

      - name: Get link to Asana Parent Task
        uses: ./actions
        id: get-parent-task-id
        with:
          action: 'get-asana-task-parent-link'
          asana-pat: ${{ secrets.asana_pat }}
          asana-task-id: ${{ steps.find-asana-task-id.outputs.asanaTaskId }}

      - name: Create Privacy Review task
        uses: ./actions
        id: create-review-task
        with:
          asana-pat: ${{ secrets.asana_pat }}
          asana-project: '1209820243661140' #'69071770703008'
          #asana-tags: '1208613272217946'
          asana-collaborators: '${{ steps.get-author-asana-id.outputs.asanaUserId }}'
          asana-task-name: 'Privacy Triage: ${{ inputs.team_name }} - ${{ github.event.pull_request.title }}'
          asana-task-description: |
            PR: ${{ github.event.pull_request.html_url }}/files?file-filters[]=.json&file-filters[]=.json5
            PR Author: https://app.asana.com/0/profile/${{ steps.get-author-asana-id.outputs.asanaUserId }}
            Project Task: ${{ steps.get-parent-task-id.outputs.asanaTaskParentLink }}
          asana-task-custom-field-category: 'Pixels'
          action: 'create-asana-task'

      - name: Add Privacy Review task to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Privacy Review task: https://app.asana.com/0/69071770703008/${{steps.create-review-task.outputs.taskId}}'
            })


      - name: Ping PR author in comment
        uses: ./actions
        id: ping-pr-author-in-comment
        with:
          asana-pat: ${{ secrets.asana_pat }}
          asana-task-id: ${{ steps.create-review-task.outputs.taskId }}
          asana-task-comment: |
            https://app.asana.com/0/profile/${{ steps.get-author-asana-id.outputs.asanaUserId }} this triage task has been created for your PR: ${{ github.event.pull_request.html_url }}
            Please check the task description, set the Objective and Priority fields, and add any context that could help speed up the review process!
          asana-task-comment-pinned: false
          action: 'post-comment-asana-task'

          # TASK_ID = core.getInput('asana-task-id'),
          # TASK_COMMENT = core.getInput('asana-task-comment')
          # IS_PINNED = core.getInput('asana-task-comment-pinned')