name: Test - Workflow for Testing

on:
  workflow_dispatch:

    inputs:
      ref:
        description: 'This is an example of an input'
        required: true

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    name: Add here whatever steps you want to test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
